#!/usr/bin/env python3
"""
Machine-generated agent context for .agents/context/.

Regenerates four files any coding agent can trust as ground truth:
  repo-map.md        directory tree + module docstrings
  api-surface.md     every FastAPI route, introspected from the live app object
  test-inventory.md  every test, collected by pytest
  db-schema.md       every table/column from the SQLAlchemy metadata

Deterministic by construction: sorted output, no timestamps, no randomness —
so running it twice yields byte-identical files, and CI can fail a PR whose
code changed the API surface without regenerating context.

Run from the repo root:  SEED_ON_STARTUP=false python scripts/generate_context.py
(CI refreshes these automatically on every push to main.)
"""
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND = REPO_ROOT / "backend"
OUT_DIR = REPO_ROOT / ".agents" / "context"

# Importing the app must stay side-effect free.
os.environ["SEED_ON_STARTUP"] = "false"
sys.path.insert(0, str(BACKEND))

HEADER = "<!-- generated by scripts/generate_context.py — do not edit by hand -->\n\n"

EXCLUDED_DIRS = {
    ".git", "node_modules", ".next", "__pycache__", "venv", ".venv",
    ".pytest_cache", ".ruff_cache", "pgdata",
}


def write(name: str, body: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / name).write_text(HEADER + body.rstrip() + "\n")
    print(f"wrote .agents/context/{name}")


def first_docstring_line(path: Path) -> str:
    import ast
    try:
        doc = ast.get_docstring(ast.parse(path.read_text()))
        return doc.strip().splitlines()[0] if doc else ""
    except SyntaxError:
        return ""


def generate_repo_map() -> None:
    lines = ["# Repository Map", ""]
    for root, dirs, files in os.walk(REPO_ROOT):
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDED_DIRS)
        rel = Path(root).relative_to(REPO_ROOT)
        if rel != Path("."):
            depth = len(rel.parts)
            lines.append(f"{'  ' * (depth - 1)}- **{rel.parts[-1]}/**")
        depth = 0 if rel == Path(".") else len(rel.parts)
        for f in sorted(files):
            if f.endswith((".pyc", ".db", ".log")) or f == ".DS_Store":
                continue
            entry = f"{'  ' * depth}- {f}"
            if f.endswith(".py"):
                doc = first_docstring_line(Path(root) / f)
                if doc:
                    entry += f" — {doc}"
            lines.append(entry)
    write("repo-map.md", "\n".join(lines))


def generate_api_surface() -> None:
    from fastapi.routing import APIRoute

    from app.main import app

    def iter_api_routes(routes):
        for route in routes:
            if isinstance(route, APIRoute):
                yield route
            # Newer FastAPI wraps include_router mounts lazily; the concrete
            # APIRoutes (with full prefixed paths) live on original_router.
            inner = getattr(getattr(route, "original_router", None), "routes", None)
            if inner:
                yield from iter_api_routes(inner)

    rows = []
    for route in iter_api_routes(app.routes):
        summary = (route.endpoint.__doc__ or "").strip().splitlines()
        summary_line = summary[0].strip() if summary else ""
        for method in sorted(route.methods - {"HEAD", "OPTIONS"}):
            rows.append((route.path, method, route.name, summary_line))
    rows = sorted(set(rows))

    lines = [
        "# API Surface",
        "",
        "Introspected from the live FastAPI app (`app.main:app`). "
        f"{len(rows)} routes.",
        "",
        "| Method | Path | Handler | Summary |",
        "|---|---|---|---|",
    ]
    for path, method, name, summary in rows:
        lines.append(f"| {method} | `{path}` | `{name}` | {summary} |")
    write("api-surface.md", "\n".join(lines))


def generate_test_inventory() -> None:
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", str(REPO_ROOT / "tests")],
        cwd=BACKEND, capture_output=True, text=True, check=False,
    )
    tests: dict[str, list[str]] = {}
    for line in proc.stdout.splitlines():
        if "::" in line and not line.startswith(" "):
            file_part, test_part = line.split("::", 1)
            tests.setdefault(Path(file_part).name, []).append(test_part.strip())

    total = sum(len(v) for v in tests.values())
    lines = [f"# Test Inventory — {total} tests", ""]
    for filename in sorted(tests):
        lines.append(f"## {filename} ({len(tests[filename])})")
        lines.extend(f"- `{t}`" for t in sorted(tests[filename]))
        lines.append("")
    lines.append("Run all: `cd backend && pytest -v ../tests/`")
    lines.append("Run one: `cd backend && pytest ../tests/<file>::<test> -v`")
    write("test-inventory.md", "\n".join(lines))


def generate_db_schema() -> None:
    from app import models  # noqa: F401  (registers all tables on Base)
    from app.database import Base

    lines = ["# Database Schema", "", "From SQLAlchemy metadata (`app.models`).", ""]
    for table in Base.metadata.sorted_tables:
        lines.append(f"## `{table.name}`")
        lines.append("")
        lines.append("| Column | Type | Nullable | Indexed |")
        lines.append("|---|---|:---:|:---:|")
        for col in table.columns:
            indexed = "✓" if (col.index or col.primary_key or col.unique) else ""
            lines.append(
                f"| `{col.name}` | {col.type} | {'✓' if col.nullable else ''} | {indexed} |"
            )
        lines.append("")
    write("db-schema.md", "\n".join(lines))


if __name__ == "__main__":
    generate_repo_map()
    generate_api_surface()
    generate_test_inventory()
    generate_db_schema()
    print("context refresh complete")
